"""add identity_documents table

Revision ID: 48271134b900
Revises: 5dfccc05bad8
Create Date: 2026-07-16 21:01:45.477818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48271134b900'
down_revision = '5dfccc05bad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cnic_image_key', sa.String(length=255), nullable=False),
    sa.Column('selfie_image_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_documents_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_documents_user_id'))

    op.drop_table('identity_documents')
    # ### end Alembic commands ###
